vich_uploader:
    db_driver: orm
    mappings:
        photoVehicule:
            uri_prefix: /img/Vehicules
            upload_destination: '%kernel.project_dir%/public/img/Vehicules'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer