controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

vehicule_etat:
    path: /vehicule/etat
    controller: App\Controller\VehiculeController::etat

assurance.index:
    path: /assurance
    controller: App\Controller\AssuranceController::index

visite.index:
    path: /visite
    controller: App\Controller\VisiteController::index

api_available_vehicles_and_drivers:
    path: /api/available-vehicles-and-drivers
    controller: App\Controller\DemandeController::availableVehiclesAndDrivers
    methods: ['POST']


